In [1]:
import numpy as np
import pandas as pd

Creating a Data Frame

In [4]:
data = {'Names' :['John', 'Anna', 'Peter', 'Linda'],
         'Age': [28, 34, 29, 42],
         'City': ['New York', 'Paris', 'Berlin', 'London'],
         'Salary': [65000, 70000, 62000, 85000] }
df = pd.DataFrame(data)
df

   Names  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
list = [
         ['John', 28, 'New York', 65000],
         ['Anna', 34, 'Paris', 70000],
         ['Peter', 29, 'Berlin', 62000],
         ['Linda', 42, 'London', 85000]
]

list1 = ['Name', 'Age', 'City', 'Salary']
df1 = pd.DataFrame(list, columns = list1)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

In [8]:
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df1['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
df1[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new Column

In [25]:
df1['Designation'] = ['Doctor', 'Engineer', 'Physiotherepist', 'Coder']
df1

    Name  Age      City  Salary      Designation
0   John   28  New York   65000           Doctor
1   Anna   34     Paris   70000         Engineer
2  Peter   29    Berlin   62000  Physiotherepist
3  Linda   42    London   85000            Coder

Removing Column(s)

In [26]:
df1.drop("Designation", axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df1

    Name  Age      City  Salary      Designation
0   John   28  New York   65000           Doctor
1   Anna   34     Paris   70000         Engineer
2  Peter   29    Berlin   62000  Physiotherepist
3  Linda   42    London   85000            Coder

In [28]:
df1.drop(['Age', 'City'], axis = 1)

    Name  Salary      Designation
0   John   65000           Doctor
1   Anna   70000         Engineer
2  Peter   62000  Physiotherepist
3  Linda   85000            Coder

Removing row(s)

In [29]:
df1.drop(0, axis = 0)

    Name  Age    City  Salary      Designation
1   Anna   34   Paris   70000         Engineer
2  Peter   29  Berlin   62000  Physiotherepist
3  Linda   42  London   85000            Coder

Selecting Row(s)

In [33]:
df1

    Name  Age      City  Salary      Designation
0   John   28  New York   65000           Doctor
1   Anna   34     Paris   70000         Engineer
2  Peter   29    Berlin   62000  Physiotherepist
3  Linda   42    London   85000            Coder

In [31]:
df1.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [32]:
df1.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000    Engineer

In [37]:
df1.iloc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation     Coder
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [39]:
df1

    Name  Age      City  Salary      Designation
0   John   28  New York   65000           Doctor
1   Anna   34     Paris   70000         Engineer
2  Peter   29    Berlin   62000  Physiotherepist
3  Linda   42    London   85000            Coder

In [36]:
df1.loc[[0,1]][['Salary', 'Designation']]

   Salary Designation
0   65000      Doctor
1   70000    Engineer

In [38]:
df1.loc[[2,3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [40]:
df1

    Name  Age      City  Salary      Designation
0   John   28  New York   65000           Doctor
1   Anna   34     Paris   70000         Engineer
2  Peter   29    Berlin   62000  Physiotherepist
3  Linda   42    London   85000            Coder

In [41]:
# I only want to see those people whosw age is greater than 30

In [42]:
df1[df1['Age'] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000       Coder

In [43]:
# I only want to see those people whose age is greater than 30 and salary is greater than 650000

In [44]:
df1[(df1['Age'] > 30) & (df1['Salary'] > 65000)]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000       Coder