Merging, Joining & Concatenation

In [1]:
import numpy as np
import pandas as pd

Merginig 2 DataFrames

In [3]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2 : Salary Infromation
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [4]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
# Inner Join

In [11]:
df1 = pd.merge(employees, salaries, on = 'employee_id', how = 'inner') 
df1

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
# Full or Outer Join

In [12]:
df2 = pd.merge(employees, salaries, on = 'employee_id', how = 'outer')
df2

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
# Left Join

In [15]:
df3 = pd.merge(employees, salaries, on = 'employee_id', how = 'left')
df3

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
# Right Join

In [16]:
df4 = pd.merge(employees, salaries, on = 'employee_id', how = 'right')
df4

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [17]:
df2

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [14]:
df2.isna().sum()

employee_id    0
name           2
department     2
salary         2
bonus          2
dtype: int64

Concatenation of 2 DataFrames

In [18]:
df5 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df6 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [19]:
df5

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [20]:
df6

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [22]:
pd.concat([df5, df6])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [23]:
pd.concat([df5, df6], axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining 2 DataFrames

In [27]:
df7 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df8 = pd.DataFrame({
    'score': [85, 90, 75]
}, index = [2, 3, 4])

In [25]:
df7

      name
1    Alice
2      Bob
3  Charlie

In [28]:
df8

   score
2     85
3     90
4     75

In [29]:
df7.join(df8)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [31]:
df7.join(df8, how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [32]:
df8.join(df7)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [33]:
df8.join(df7, how = 'outer')

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN